### ISSUE TITLE
Secondary x axis in figure with multiple subplots

### ISSUE THREAD

**Issue by kinverarity1** [WesleyTheGeolien/t20-Dash_Well_Viz#15]
![image](https://user-images.githubusercontent.com/4525931/83968651-da455c80-a909-11ea-9a22-0f5e4dcfd54d.png)

@dougmcclymont  needing this for filling between logs too.

Plotly docs are not much use: https://plotly.com/python/multiple-axes/

I don't think this helps us: https://github.com/plotly/plotly.py/issues/1553

Very ugly hack solution which would work but I feel tired just thinking about how it would cause trouble later on: https://stackoverflow.com/questions/54232879/secondary-parallel-x-axis-on-plotly-charts-python

**Comment by WesleyTheGeolien** [comment]
So there is a way to add an extra xaxis like showed in the docs, this works fine for displaying both values close to each other but from my understanding it would also be useful to color between the curves, this appears to be non trivial as they are on different axis, at least from what I have seen so far.

To do coloring I think normalizing the data maybe the way forward.

**Comment by WesleyTheGeolien** [comment]
This issue should be adressed in PR #20
